In [1]:
import numpy as np
from numpy.linalg import matrix_power
from numpy.linalg import inv

import networkx as nx
import matplotlib as plt

In [2]:
#
# V1 = 5 -- N1 -- R1 = 100 -- N2 -- R2 = 100 -- N3
#
#

In [3]:
num_nodes = 2; 
num_sources = 1;  

V1 = 5; 
R1 = 100; 
R2 = 100; 

G1 = 1 / R1; 
G2 = 1 / R2; 

G = np.zeros((num_nodes, num_nodes)); 
V = np.zeros((num_nodes, num_sources)); 
Z = np.zeros((num_sources, num_sources)); 

G[0,0] = G1; 
G[1,1] = G1 + G2; 
G[1,0] = -G1; 
G[0,1] = -G1; 

V[0,0] = V1; 

V_T = np.transpose(V); 

M_1 = np.concatenate((G, V), axis = 1); 
M_2 = np.concatenate((V_T, Z), axis = 1); 

M = np.concatenate((M_1, M_2), axis = 0); 

I_M = inv(np.matrix(M)); 

print(I_M)

knowns = np.array([[0], [0], [V1]]); 

print(knowns)

unknowns = I_M * knowns; 

print(unknowns); 



[[ 0.e+00  0.e+00  2.e-01]
 [ 0.e+00  5.e+01  1.e-01]
 [ 2.e-01  1.e-01 -2.e-04]]
[[0]
 [0]
 [5]]
[[ 1.   ]
 [ 0.5  ]
 [-0.001]]
